config/routes.rb
Gbchaosmaster::Application.routes.draw do
  root to: "home#index"

  match "/about", to: "pages#about"
  match "/contact", to: "pages#contact"

  match "/projects", to: "projects#index"
  match "/projects/nds_toolkit", to: "projects#nds_toolkit"
  match "/projects/nutella", to: "projects#nutella"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end

  def nds_toolkit
  end

  def nutella
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # If there is a controller-specific stylesheet, return the link to that
  # stylesheet. Otherwise, return <tt>nil</tt>.
  def controller_specific_stylesheet
    name = controller.controller_name
    if Rails.application.assets.find_asset "#{name}.css"
      stylesheet_link_tag name, media: "all"
    end
  end

  # Generates a generic page title. Prepend +title+ with "gbchaosmaster" and a
  # pipe for separation. If +title+ is blank, simply return "gbchaosmaster".
  #
  #   page_title "Test Page"  # => "gbchaosmaster | Test Page"
  #   page_title nil          # => "gbchaosmaster"
  def page_title(title)
    "gbchaosmaster#{" | #{title}" unless title.blank?}"
  end

  # Generates a link for a navigation bar. It is an <tt>li</tt> element and
  # will have the <tt>active</tt> class if the current location is in +paths+.
  #
  #   # If the current page is the root of the website:
  #   nav_link "Home", root_path
  #     # => '<li class="active"><a href="/">Home</a></li>'
  #
  #   # If the current page is not the root of the website:
  #   nav_link "Home", root_path  # => '<li><a href="/">Home</a></li>'
  #
  # If multiple paths are passed in, it will be active if any of the paths
  # match. The inner <tt>a</tt> tag will always link to the first path.
  #
  #   # If the current page is either the about page or the contact page:
  #   nav_link "Some Pages", about_path, contact_path
  #     # => '<li class="active"><a href="/about">Some Pages</a></li>'
  #
  #   # If the current page is neither the about page nor the contact page:
  #   nav_link "Some Pages", about_path, contact_path
  #     # => '<li><a href="/about">Some Pages</a></li>'
  def nav_link(text, *paths)
    attrs = paths.any? { |p| current_page?(p) } ? { :class => "active" } : {}
    content_tag(:li, attrs) { link_to text, paths.first }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.haml
%h1 gbchaosmaster
%p This website is currently in development! This is the home page.

app/views/layouts/_footer.html.erb
<div class="footer container">
  <div class="row-fluid">
    <div class="span4 left">
      Source code available on
      <%= link_to "GitHub", "https://github.com/gbchaosmaster/gbchaosmaster" %>.
    </div>
    <div class="span4">Copyright ©2012 Vinny Diehl</div>
    <div class="span4 right">
      <%= link_to "Contact the Developer", contact_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.haml
!!! 5

%html
  %head
    %title= page_title(yield :title)

    = stylesheet_link_tag "application", media: "all"
    = controller_specific_stylesheet
    = javascript_include_tag "application"

    = csrf_meta_tags

    -# Responsive page width on mobile devices
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}/

    = render "layouts/application/shim"

  %body
    = render "layouts/application/nav"
    .container-fluid
      .row-fluid
        -# The main yielded content is rendered here.
        = content_for?(:content) ? yield(:content) : yield
      .row-fluid
        = render "layouts/application/footer"

app/views/layouts/application/_footer.html.haml
- content_for :github_link do
  Source code available on
  = succeed "." do
    %a{href: "https://github.com/gbchaosmaster/gbchaosmaster"} GitHub

- content_for :copyright do
  Copyright ©2012 Vinny Diehl

- content_for :contact_link do
  = link_to "Contact the Developer", contact_path

.footer

  -# On most screens the footer text will distribute evenly across the bottom.
  -# On phones, it will appear stacked at the bottom.

  .hidden-phone
    .span4.left
      = yield :github_link
    .span4
      = yield :copyright
    .span4.right
      = yield :contact_link

  .visible-phone{align: "center"}
    = yield :github_link
    %br/
    = yield :copyright
    %br/
    = yield :contact_link

app/views/layouts/application/_nav.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container-fluid

      -# This is the navigation toggle button- it only shows when the nav bar
      -# is in collapse mode.
      %a.btn.btn-navbar{"data-toggle" => "collapse",
                        "data-target" => ".nav-collapse"}
        - 3.times do
          %span.icon-bar

      = link_to "gbchaosmaster", root_path, class: "brand"

      .nav-collapse.collapse
        %ul.nav.pull-right
          = nav_link "Home", root_path

          -# Projects Dropdown
          %li.dropdown
            %a.dropdown-toggle{href: "#", "data-toggle" => "dropdown"}
              Projects
              %b.caret
            %ul.dropdown-menu
              = nav_link "Projects Home", projects_path

              %li.divider

              %li.nav-header Applications
              = nav_link "NDS Toolkit", projects_nds_toolkit_path

              %li.divider

              %li.nav-header Libraries
              = nav_link "Nutella", projects_nutella_path
          -# End Projects Dropdown

          = nav_link "About", about_path

app/views/layouts/application/_shim.html.haml
-# HTML5 Shim for IE 6-8
/[if lt IE 9]
  %script{src: "http://html5shim.googlecode.com/svn/trunk/html5.js"}

app/views/layouts/projects.html.haml
- content_for :content do
  .span3
    = render "layouts/projects/sidebar"
  .span9
    = yield

= render file: "layouts/application"

app/views/layouts/projects/_sidebar.html.haml
.well.sidebar-nav
  %ul.nav.nav-list
    %li.nav-header Applications
    = nav_link "NDS Toolkit", projects_nds_toolkit_path
    %li.nav-header Libraries
    = nav_link "Nutella", projects_nutella_path

app/views/pages/about.html.haml
- provide :title, "About"

%h1 About gbchaosmaster
%p This is gonna be my about page.

app/views/pages/contact.html.haml
- provide :title, "Contact"

%h1 Contact
%p This is gonna be my "contact me" page.

app/views/projects/index.html.haml
- provide :title, "Projects"

%h1 Projects
%p
  This section is where all of my projects will go. This page will be a brief
  introduction to them.

app/views/projects/nds_toolkit.html.haml
- provide :title, "NDS Toolkit"

.hero-unit
  %h1 NDS Toolkit
  %p NDS Toolkit is a suite of tools for hacking Nintendo games.
  %p
    It is a fork of the original by Demonic722, made to be cross-platform
    and given a few personal touches.

.row-fluid
  .span6.well
    %h2 Button Activator Generator
    %p
      This tool automates the process of finding an activator for your codes.
      Simply give the tool your code, select the buttons that you wish to have
      activate it, and your final code will be given to you.
    %a.btn.btn-primary{href: "#"} Learn more &raquo;
  .span6.well
    %h2 Pointer Searcher
    %p
      Input two RAM dumps and this tool will search for pointers, and find the
      result with the smallest offset. Select a result to generate ARDS code
      for that result.
    %a.btn.btn-primary{href: "#"} Learn more &raquo;

.row-fluid
  .span6.well
    %h2 Code Porter
    %p
      This tool makes region ports with a specific offset a snap. Simply enter
      the code that you wish to port, select the offset that you wish to use,
      and your code will be ported.
    %a.btn.btn-primary{href: "#"} Learn more &raquo;
  .span6.well
    %h2 Code Beautifier
    %p
      This is a front-end to the built-in automatic code beautifier. If you
      have poorly formatted code that you wish to be arranged into two neat
      columns, use this tool.
    %a.btn.btn-primary{href: "#"} Learn more &raquo;

.row-fluid
  .span6.well
    %h2 Loop Code Generator
    %p
      This is part of the Code Compressor, a tool designed to loop ARDS codes,
      shortening them. The Loop Code Generator will start with a base code,
      increment the address of that code, and optionally loop the value of that
      code as it advances to the next address.
    %a.btn.btn-primary{href: "#"} Learn more &raquo;
  .span6.well
    %h2 Patch Code Builder
    %p
      This is the second part of the Code Compressor. It compresses code with
      addresses that continually increment by 4, but values that have no
      pattern to them.
    %a.btn.btn-primary{href: "#"} Learn more &raquo;

.row-fluid
  .span4
    %h2 Open Source
    %p
      Everything about the NDS Toolkit is completely open- its code is
      available to the public, and anybody can help with the project! Click
      below to see how you can contribute.
    %a.btn{href: "#"} Learn more &raquo;
  .span4
    %h2 Customizable
    %p
      The NDS Toolkit is made to be customizable. You can configure how it is
      built, so you don't have to have anything that isn't useful to you.
    %a.btn{href: "#"} Learn more &raquo;
  .span4
    %h2 Useable
    %p
      The NDS Toolkit is designed to be as intuitive and usable as possible-
      click below to check out some of the features designed to prevent user
      frustration.
    %a.btn{href: "#"} Learn more &raquo;

app/views/projects/nutella.html.haml
- provide :title, "Nutella"

.hero-unit
  %h1 Nutella
  %p Spread some Nutella on Ruby to sweeten up its functionality!
  %p
    Nutella is a collection of utilities and core extensions for Ruby. It is
    a constant work in progress, so get into it and if you have any ideas,
    feel free to chip in!